title: "Gleb's Neo Cortex"
author: "Gleb Razgar"
description: "My prefrontal cortex at your disposal"

# Email / Social media user names used by the minima theme:
email: "gleb.studios@gmail.com"
twitter_username: "gleb_razgar"
github_username: "ProjectGleb"
linkedin_username: "gleb-razgar-6931a7220"

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

# rss: rss
permalink: /:title/

kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

collections:
  research:
    output: true
    permalink: /:title/
  duality:
    output: true
    permalink: Duality/:title/
  duality-research:
    output: true
    permalink: /Duality/Research/:title/
defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
  - scope:
      path: ""
    values:
      mathjax: true
  - scope:
      path: "images"
    values:
      image: true

include:
  - "images"
  - "*.gif"